- hosts: vagrantAWS-Ancillary1
# hosts: vagrantAWS-Ancillary
  #- hosts: wdcreancil02
  vars:  
    custom_repo: true
  vars_files:
    - ~/RHACCOUNT
  become: yes
  become_method: sudo

# COMMON for Research Environment
# roles:
#   - {role: iptables, when: "iptables_config"}
#   - {role: common, when: "install_glusterfs"}
#   - {role: epel, when: "use_epel and not 'production' in group_names"}
#   - emacs
#   - jdk
#   - odbc
#   - postgresql-client
# post_tasks:
#   - name: research eod symlinks
#     file:
#        src: "{{ item.src }}"
#        dest: "{{ item.dest }}"
#     with_items: "{{ eod_symlinks }}"

#   - name: Install xauth dependency
#     yum:
#       name: xorg-x11-xauth
#       state: present

#   - name: Ensure X11 Forwarding is present
#     lineinfile:
#       dest: /etc/ssh/sshd_config
#       regexp: ^\s*X11Forwarding\s*no
#       line: X11Forwarding yes
#     when: not custom_repo

#   - name: Ensure ClientAliveCountMax is set to correct value
#     lineinfile:
#       dest: /etc/ssh/sshd_config
#       regexp: ^\s*ClientAliveCountMax\s*[0-9]+
#       line: ClientAliveCountMax 384
#     when: not custom_repo

#   - name: Ensure run level 5
#     lineinfile:
#       dest: /etc/inittab
#       regexp: initdefault
#       line: "id:5:initdefault:"

#   - name: research printers symlinks
#     file:
#       state: link
#       src: "{{ item.src }}"
#       dest: "{{ item.dest }}"
#     with_items: "{{ printers_symlinks }}"

#   - name: Install git
#     yum:
#       name: git
#       state: present



  pre_tasks:
    - debug:
#       msg: "Variables: _uid = {{ _uid }}, _pwd = **********"
        msg: "Variables: _uid = {{ _uid }}, _pwd = {{ _pwd }}"
    - name: register RHEL7.5
      command: "/usr/bin/subscription-manager register --username {{ _uid }} --password {{ _pwd }} --auto-attach --force"
#     when: _uid != "" and _pwd != ""
#     command: "/usr/bin/subscription-manager register --username <name> --password <password> --auto-attach"
    - name: register RHEL7 repo
      command: "/usr/bin/subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-optional-rpms"
    - name: register RHEL7 RHSCL Repo
      shell: "/usr/bin/subscription-manager repos --enable=rhel-server-rhscl-7-rpms"
    - name: register RHEL7 DevTools
      shell: "/usr/bin/subscription-manager repos --enable=rhel-7-server-devtools-rpms"
    - name: list RHEL enabled repos
      shell: "/usr/bin/subscription-manager repos --list-enabled"
      register: enabled_repos
    - debug:
        msg: "RHEL Enabled Repos: {{ enabled_repos }}" 

## Move from tasks to pretasks to run before roles

#   - name: Install python-pip
#     shell: yum install -y python27 python-pip
#     yum:
#       name: python27,python-pip
#       state: present
       
#   - name: SCL Enabled Pip Install Upgrade Pip
#     shell: |
#       scl enable python27 -- pip install --upgrade pip
#     become: yes
#     become_method: sudo

    - name: install python27-python-pip
      yum:
        name: python27-python-pip
        state: present

    - name: install gdown
      shell: |
        scl enable python27 -- pip install gdown
      become: yes
      become_method: sudo
#     shell: pip install gdown  
#     yum:
#       name: gdown
#       state: present
#       disable_gpg_check: yes

    - name: check if file is already there
      stat:
        path: /tmp/ancilRH7_repo.tar.gz
      register: ancilrepo

#     Already secure copy to destination host
    - name: use gdown to download and build local repo
      become: yes
      become_method: sudo
      command: /opt/rh/python27/root/usr/bin/gdown https://drive.google.com/uc?id=1qaZH9_SrGyjHjWT3P2WtvZAhEkP9YG1Z -O /tmp/ancilRH7_repo.tar.gz
#     shell: /opt/rh/python27/root/usr/bin/gdown https://drive.google.com/uc?id=1qaZH9_SrGyjHjWT3P2WtvZAhEkP9YG1Z -O /tmp/ancilRH7_repo.tar.gz
      when: ancilrepo.stat.exists == false

#     shell: gdown https://drive.google.com/uc?id=139Z0MfyT0WVWIzP_uwM2KxPCrfYs_vUV
#   - name: Install pip
#     easy_install:
#       name: pip
#       state: latest
#   - name: Build custom local repo
#     shell: wget https://drive.google.com/open?id=1qaZH9_SrGyjHjWT3P2WtvZAhEkP9YG1Z /tmp
    - name: make localrepo directory
      shell: mkdir -p /opt/ancillary_local
    - name: make OpenOffice directory
      shell: mkdir -p /opt/ancillary_local/OO416
    - name: make Sublime3 directory
      shell: mkdir -p /opt/ancillary_local/Sublime3
    - name: make Sublime3 install directory
      shell: mkdir -p /usr/local/sublime
    - name: make stattransfer14 install directory
      shell: mkdir -p /usr/local/StatTransfer14

    - name: make /artifacts dir
      shell: mkdir -p /artifacts
    - name: check if symlink exists
      stat: path=/artifacts/stlinux64_install
      register: symlink
    - name: create Symlink for stattransfer14 executable
      shell: ln -s /opt/ancillary_local/stlinux64_install /artifacts/stlinux64_install
      when: symlink.stat.exists == False

    - name: Extract repo to destination point
      shell:  tar xvf /tmp/ancilRH7_repo.tar.gz -C /opt/ancillary_local
    - name: Extract OpenOffice 4.1.6 
      shell:  tar xvf /opt/ancillary_local/Apache_OpenOffice_4.1.6_Linux_x86-64_install-rpm_en-US.tar.gz -C /opt/ancillary_local/OO416 
    - name: install bz2
      yum:
        name: bzip2

    - name: Extract Sublime3 
      shell:  tar xvf /opt/ancillary_local/sublime_text_3_build_3207_x64.tar.bz2 -C /opt/ancillary_local/Sublime3

    - name: Extract Sublime3 to install dir
      shell:  tar xvf /opt/ancillary_local/sublime_text_3_build_3207_x64.tar.bz2 -C /usr/local/sublime 

    - name: install createrepo
      yum:
        name: createrepo
        state: latest
    - name: create local repo 
      shell: createrepo /opt/ancillary_local/OO416
#     shell: createrepo /opt/devrepo-master/Packages
    - name: create local repo file with updated link
      file:
        path: /etc/yum.repos.d/local.repo
        state: touch
        mode: "u=rw,g=r,o=r" 
    - name: edit local.repo file
      shell: |
        echo '[localrepo]
        name=localrepo
        baseurl=file:///opt/ancillary_local/OO416
        enabled=1
        gpgcheck=0' >> /etc/yum.repos.d/local.repo


  tasks:
# updated with epel7
#   - name: download epel
#     shell:  wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -O /tmp/epel-release-latest-7.noarch.rpm   
#   - name: Install epel
#     shell:  yum -y localinstall /tmp/epel*rpm

    - name: install X Window System
      shell: yum -y groupinstall "X Window System"
# replace with yum
#   - name: install XFCE
#     shell: yum -y groupinstall "xfce"

    - name: install XFCE4 Desktop
      yum:
        name: "@xfce"
        state: present
      register: xfce4desktop

#- debug: var="{{ xfce4desktop.stdout }}"
    - name: update libraries for MATE installation
      command: yum -y update --enablerepo=epel-testing

#   - name: install Evince
#     shell: yum -y install evince
    - name: install mousepad
      shell: yum -y install mousepad
#   - name: create texteditor.desktop
#     shell: |
#       echo '[Desktop Entry]
#       Version=1.0
#       Type=Application
#       Name=TextEditor
#       Comment=Mousepad
#       Exec=mousepad
#       Icon=accessories-text-editor
#       Path=
#       Terminal=false
#       StartupNotify=true' >> /home/vagrant/Desktop/texteditor.desktop
    - name: Install python-pip
      shell: yum install -y python27 python-pip
    - name: install gdown
      shell: pip install gdown  
#     yum:
#       name: python27-python-pip
#       state: latest
    - name: Install python 3.6 and pip
      shell: yum install -y python36 python36-pip
    - name: Install bash autocomplete
      shell: yum install -y bash-completion bash-completion-extras

#   - name: enable scl
#     become: yes
#     become_method: sudo
#     shell: scl enable python27 bash
#   - name: install gdown
#     shell: /opt/rh/python27/root/usr/bin/pip install gdown

##     Already secure copy to destination host
#    - name: use gdown to download and build local repo
#      shell: gdown https://drive.google.com/uc?id=1qaZH9_SrGyjHjWT3P2WtvZAhEkP9YG1Z -O /tmp/ancilRH7_repo.tar.gz
#
##     shell: gdown https://drive.google.com/uc?id=139Z0MfyT0WVWIzP_uwM2KxPCrfYs_vUV
##   - name: Install pip
##     easy_install:
##       name: pip
##       state: latest
##   - name: Build custom local repo
##     shell: wget https://drive.google.com/open?id=1qaZH9_SrGyjHjWT3P2WtvZAhEkP9YG1Z /tmp
#    - name: make localrepo directory
#      shell: mkdir -p /opt/ancillary_local
#    - name: make OpenOffice directory
#      shell: mkdir -p /opt/ancillary_local/OO416
#    - name: make Sublime3 directory
#      shell: mkdir -p /opt/ancillary_local/Sublime3
#    - name: make Sublime3 install directory
#      shell: mkdir -p /usr/local/sublime
#    - name: make stattransfer14 install directory
#      shell: mkdir -p /usr/local/StatTransfer14
#
#    - name: make /artifacts dir
#      shell: mkdir -p /artifacts
#    - name: check if symlink exists
#      stat: path=/artifacts/stlinux64_install
#      register: symlink
#    - name: create Symlink for stattransfer14 executable
#      shell: ln -s /opt/ancillary_local/stlinux64_install /artifacts/stlinux64_install
#      when: symlink.stat.exists == False
#
#    - name: Extract repo to destination point
#      shell:  tar xvf /tmp/ancilRH7_repo.tar.gz -C /opt/ancillary_local
#    - name: Extract OpenOffice 4.1.6 
#      shell:  tar xvf /opt/ancillary_local/Apache_OpenOffice_4.1.6_Linux_x86-64_install-rpm_en-US.tar.gz -C /opt/ancillary_local/OO416 
#    - name: install bz2
#      yum:
#        name: bzip2
#
#    - name: Extract Sublime3 
#      shell:  tar xvf /opt/ancillary_local/sublime_text_3_build_3207_x64.tar.bz2 -C /opt/ancillary_local/Sublime3
#
#    - name: Extract Sublime3 to install dir
#      shell:  tar xvf /opt/ancillary_local/sublime_text_3_build_3207_x64.tar.bz2 -C /usr/local/sublime 
#
#    - name: install createrepo
#      yum:
#        name: createrepo
#        state: latest
#    - name: create local repo 
#      shell: createrepo /opt/ancillary_local/OO416
##     shell: createrepo /opt/devrepo-master/Packages
#    - name: create local repo file with updated link
#      file:
#        path: /etc/yum.repos.d/local.repo
#        state: touch
#        mode: "u=rw,g=r,o=r" 
#    - name: edit local.repo file
#      shell: |
#        echo '[localrepo]
#        name=localrepo
#        baseurl=file:///opt/ancillary_local/OO416
#        enabled=1
#        gpgcheck=0' >> /etc/yum.repos.d/local.repo

  roles:
#   - umask
#   - devtools
    - epel7
    - devtools7
#   - open_office
    - open_officeRH7
#   - evince
#   See line #39 (evince)
#   - stattransfer
    - stattransfer14
#   - sublime
    - sublime3
#   - ultra-edit
    - ultra-editRH7
#   - texliveRH7

  post_tasks:
#   - name: register mime types
#     shell: update-mime-database /usr/share/mime/packages/
#   - name: create desktop application
#     shell: 
#   - name: update desktop database
#     shell: update-desktop-database ~/.local/share/applications
#   - name: Install texlive
#     yum:
#       name: texlive2016
#       state: present

#   - name: remove RHEL7.5
#     command:  "/usr/bin/subscription-manager remove --all"
#   - name: unregister RHEL7.5
#     command:  "/usr/bin/subscription-manager unregister"
#   - name: clean RHEL7.5
#     command:  "/usr/bin/subscription-manager clean"
