---
- ec2_vol:
    instance: {{ instance_id }}
    volume_size: 100
    device_name: sdb
#   Add iops  params
#   iops: 100

#
# Example: Launch an instance and then add a volume if not already attached
#   * Volume will be created with the given name if not already created.
#   * Nothing will happen if the volume is already attached.
#   * Requires Ansible 2.0

#- ec2:
#   keypair: "{{ keypair }}"
#   image: "{{ image }}"
#   zone: YYYYYY
#   id: my_instance
#   wait: yes
#   count: 1
# register: ec2

#- ec2_vol:
#   instance: "{{ item.id }}"
#   name: my_existing_volume_Name_tag
#   device_name: /dev/xvdf
# loop: "{{ ec2.instances }}"
# register: ec2_vol

# Remove a volume
#- ec2_vol:
#   id: vol-XXXXXXXX
#   state: absent

# Detach a volume (since 1.9)
#- ec2_vol:
#   id: vol-XXXXXXXX
#   instance: None

# List volumes for an instance
#- ec2_vol:
#   instance: i-XXXXXX
#   state: list

# Create new volume using SSD storage
#- ec2_vol:
#   instance: XXXXXX
#   volume_size: 50
#   volume_type: gp2
#   device_name: /dev/xvdf

# Attach an existing volume to instance. The volume will be deleted upon instance termination.
#- ec2_vol:
#   instance: XXXXXX
#   id: XXXXXX
#   device_name: /dev/sdf
#   delete_on_termination: yes
